name: shackleton
description: A File System Explorer.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.5

environment:
  sdk: '>=3.8.0'

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  async: ^2.12.0
  collection: ^1.18.0
  convert: ^3.1.2
  crypto: ^3.0.5
  cupertino_icons: ^1.0.8
  device_info_plus: ^10.0.1
  exif: ^3.3.0
  ffi: ^2.1.4
  file_icon: ^1.0.0
  flutter_map: ^8.1.1
  flutter_math_fork: ^0.7.4
  flutter_riverpod: ^3.0.1
  freezed: ^3.2.3
  freezed_annotation: ^3.0.0
  gpt_markdown: ^1.0.18
  http: ^1.4.0
  image: ^4.3.0
  intersperse: ^2.0.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  latlong2: ^0.9.0
  logger: ^2.4.0
  media_kit: ^1.1.11
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.5
  media_kit_libs_macos_video: ^1.1.4
  media_kit_libs_windows_video: ^1.0.10
  media_kit_libs_linux: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.4
  pdfrx: ^2.2.24
  process_run: ^1.2.2
  riverpod_annotation: ^3.0.3
  scrollable_positioned_list: ^0.3.8
  sqflite_common_ffi: ^2.3.4
  super_context_menu: ^0.9.1
  super_drag_and_drop: ^0.9.1
  super_native_extensions: ^0.9.1
  syncfusion_flutter_gauges: ^32.1.25
  synchronized: ^3.2.0
  universal_disk_space: ^0.2.3
  url_launcher: ^6.3.1
  version: ^3.0.2
  window_manager: ^0.5.1
  win32: ^5.13.0

dev_dependencies:
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.5
  innosetup: ^0.1.3
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/explorer.png

flutter_launcher_icons:
  image_path: 'assets/explorer.png'
  remove_alpha_ios: true
  macos:
    generate: true
  android: false
  windows:
    generate: true
  ios: false
  web:
    generate: false
